# Site settings
title: byte-sized
header-img: images/site-resources/home.jpg
email: your-email@yourdomain.com
copyright_name: spencerdodd
description: "blog about my coding and security work"
baseurl: "/"
url: "https://spencerdodd.github.io"
github_username:  spencerdodd

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
